[colors]
foreground = "#cfbcba"
background = "#0f0e06"
cursor_bg = "#ffaa33"
cursor_border = "#ffaa33"
cursor_fg = "#0f0e06"
selection_bg = "#3f1324"
selection_fg = "#cfbcba"
split = "#58514f"
compose_cursor = "#c48702"
scrollbar_thumb = "#302a3a"

ansi = ["#0f0e06", "#ef656a", "#2fa526", "#c48702", "#379cf6", "#d570af", "#4fb0cf", "#887c8a"]
brights = ["#56524f", "#f06a3f", "#64aa0f", "#d0730f", "#6a88ff", "#e580ea", "#6fafff", "#cfbcba"]

[colors.tab_bar]
inactive_tab_edge = "#25241d"
background = "#0f0e06"

[colors.tab_bar.active_tab]
fg_color = "#0f0e06"
bg_color = "#70a89f"

[colors.tab_bar.inactive_tab]
fg_color = "#70a89f"
bg_color = "#26211d"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#70a89f"
bg_color = "#302a3a"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#2fa526"
bg_color = "#0f0e06"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#379cf6"
bg_color = "#0f0e06"

[metadata]
aliases = []
author = "prot"
name = "ef-autumn"