[colors]
foreground = "#d3cfcf"
background = "#190a0f"
cursor_bg = "#ff5aaf"
cursor_border = "#ff5aaf"
cursor_fg = "#190a0f"
selection_bg = "#232f3f"
selection_fg = "#d3cfcf"
split = "#695960"
compose_cursor = "#e5b76f"
scrollbar_thumb = "#401f33"

ansi = ["black", "#ff7359", "#60b444", "#e5b76f", "#8fa5f6", "#ef80bf", "#8fbaef", "gray65"]
brights = ["gray35", "#ff656f", "#60bf88", "#ea9955", "#a897ef", "#df7fff", "#8fcfdf", "white"]

[colors.tab_bar]
inactive_tab_edge = "#594a4f"
background = "#190a0f"

[colors.tab_bar.active_tab]
fg_color = "#190a0f"
bg_color = "#bf9cdf"

[colors.tab_bar.inactive_tab]
fg_color = "#bf9cdf"
bg_color = "#392a2f"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#bf9cdf"
bg_color = "#401f33"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#60b444"
bg_color = "#190a0f"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#8fa5f6"
bg_color = "#190a0f"

[metadata]
aliases = []
author = "prot"
name = "ef-cherie"