[colors]
foreground = "#d0d0d0"
background = "#000000"
cursor_bg = "#ff76ff"
cursor_border = "#ff76ff"
cursor_fg = "#000000"
selection_bg = "#2a234a"
selection_fg = "#d0d0d0"
split = "#4f4f5f"
compose_cursor = "#bf9032"
scrollbar_thumb = "#002435"

ansi = ["#000000", "#ef6560", "#0faa26", "#bf9032", "#3f95f6", "#d369af", "#4fbaef", "#857f8f"]
brights = ["#4b4b4b", "#f47360", "#6aad0f", "#d1843f", "#6a9fff", "#e580ea", "#6fafff", "#d0d0d0"]

[colors.tab_bar]
inactive_tab_edge = "#222222"
background = "#000000"

[colors.tab_bar.active_tab]
fg_color = "#000000"
bg_color = "#89afef"

[colors.tab_bar.inactive_tab]
fg_color = "#89afef"
bg_color = "#1a1a1a"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#89afef"
bg_color = "#002435"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#0faa26"
bg_color = "#000000"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#3f95f6"
bg_color = "#000000"

[metadata]
aliases = []
author = "prot"
name = "ef-dark"