[colors]
foreground = "#d0d0d0"
background = "#070019"
cursor_bg = "#ef6f11"
cursor_border = "#ef6f11"
cursor_fg = "#070019"
selection_bg = "#042a50"
selection_fg = "#d0d0d0"
split = "#545f6f"
compose_cursor = "#c48702"
scrollbar_thumb = "#301a4f"

ansi = ["black", "#ef656a", "#50a22f", "#c48702", "#6f80ff", "#d369af", "#5faaef", "gray65"]
brights = ["gray35", "#f47360", "#00b982", "#d0730f", "#029fff", "#af85ff", "#0dafdf", "white"]

[colors.tab_bar]
inactive_tab_edge = "#4a4759"
background = "#070019"

[colors.tab_bar.active_tab]
fg_color = "#070019"
bg_color = "#89afef"

[colors.tab_bar.inactive_tab]
fg_color = "#89afef"
bg_color = "#2a2739"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#89afef"
bg_color = "#301a4f"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#1fa526"
bg_color = "#070019"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#379cf6"
bg_color = "#070019"

[metadata]
aliases = []
author = "prot"
name = "ef-duo-dark"