[colors]
foreground = "#eaf2ef"
background = "#222524"
cursor_bg = "#ef7fa8"
cursor_border = "#ef7fa8"
cursor_fg = "#222524"
selection_bg = "#543040"
selection_fg = "#eaf2ef"
split = "#5d5f63"
compose_cursor = "#cac85f"
scrollbar_thumb = "#2f413f"

ansi = ["NONE", "#ff656a", "#7fc87f", "#cac85f", "#57aff6", "#f59acf", "#7fcfdf", "NONE"]
brights = ["NONE", "#ff7a5f", "#50cf89", "#e0b02f", "#78afff", "#cfaaff", "#60d5c2", "NONE"]

[colors.tab_bar]
inactive_tab_edge = "#5e6160"
background = "#222524"

[colors.tab_bar.active_tab]
fg_color = "#222524"
bg_color = "#8fcfbb"

[colors.tab_bar.inactive_tab]
fg_color = "#8fcfbb"
bg_color = "#3e4140"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#8fcfbb"
bg_color = "#2f413f"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#7fc87f"
bg_color = "#222524"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#57aff6"
bg_color = "#222524"

[metadata]
aliases = []
author = "prot"
name = "ef-elea-dark"