[colors]
foreground = "#232323"
background = "#fcffff"
cursor_bg = "#0055bb"
cursor_border = "#0055bb"
cursor_fg = "#fcffff"
selection_bg = "#d4eaf3"
selection_fg = "#232323"
split = "#b0b7c0"
compose_cursor = "#aa6100"
scrollbar_thumb = "#dff6e4"

ansi = ["NONE", "#c42d2f", "#008a00", "#aa6100", "#4244ef", "#aa44c5", "#3a6dd2", "NONE"]
brights = ["NONE", "#cf2f4f", "#00845f", "#996c4f", "#065fff", "#7f5ae0", "#1f6fbf", "NONE"]

[colors.tab_bar]
inactive_tab_edge = "#b5b8b8"
background = "#fcffff"

[colors.tab_bar.active_tab]
fg_color = "#fcffff"
bg_color = "#204f9a"

[colors.tab_bar.inactive_tab]
fg_color = "#204f9a"
bg_color = "#d7dbdb"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#204f9a"
bg_color = "#dff6e4"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#008a00"
bg_color = "#fcffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#004fc0"
bg_color = "#fcffff"

[metadata]
aliases = []
author = "prot"
name = "ef-frost"