[colors]
foreground = "#232323"
background = "#fcffff"
cursor_bg = "#0055bb"
cursor_border = "#0055bb"
cursor_fg = "#fcffff"
selection_bg = "#d4eaf3"
selection_fg = "#232323"
split = "#b0b7c0"
compose_cursor = "#aa6100"
scrollbar_thumb = "#dff6e4"

ansi = ["#232323", "#c42d2f", "#008a00", "#aa6100", "#004fc0", "#aa44c5", "#1f6fbf", "#b5b8b8"]
brights = ["#66657f", "#d03003", "#468400", "#b6532f", "#4244ef", "#c0469a", "#3a6dd2", "#fcffff"]

[colors.tab_bar]
inactive_tab_edge = "#ecf0f0"
background = "#fcffff"

[colors.tab_bar.active_tab]
fg_color = "#fcffff"
bg_color = "#204f9a"

[colors.tab_bar.inactive_tab]
fg_color = "#204f9a"
bg_color = "#eaefef"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#204f9a"
bg_color = "#dff6e4"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#008a00"
bg_color = "#fcffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#004fc0"
bg_color = "#fcffff"

[metadata]
aliases = []
author = "prot"
name = "ef-frost"