[colors]
foreground = "#eeffff"
background = "#292d3e"
cursor_bg = "#ff66ff"
cursor_border = "#ff66ff"
cursor_fg = "#292d3e"
selection_bg = "#3c435e"
selection_fg = "#eeffff"
split = "#61647a"
compose_cursor = "#d0bc00"
scrollbar_thumb = "#303a6f"

ansi = ["#292d3e", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "gray50"]
brights = ["#292d3e", "#ff6b55", "#70b900", "#fec43f", "#79a8ff", "#f78fe7", "#4ae2f0", "#eeffff"]

[colors.tab_bar]
inactive_tab_edge = "#2b3045"
background = "#292d3e"

[colors.tab_bar.active_tab]
fg_color = "#292d3e"
bg_color = "#c6daff"

[colors.tab_bar.inactive_tab]
fg_color = "#c6daff"
bg_color = "#1d2235"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c6daff"
bg_color = "#303a6f"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#44bc44"
bg_color = "#292d3e"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#2fafff"
bg_color = "#292d3e"

[metadata]
aliases = []
author = "prot"
name = "ef-false"