[colors]
foreground = "#202020"
background = "#ffffff"
cursor_bg = "#0033cc"
cursor_border = "#0033cc"
cursor_fg = "#ffffff"
selection_bg = "#bfefff"
selection_fg = "#202020"
split = "#bfc4da"
compose_cursor = "#a45f22"
scrollbar_thumb = "#e4efd8"

ansi = ["NONE", "#d51272", "#217a3c", "#a45f22", "#4250ef", "#ba35af", "#1f6fbf", "NONE"]
brights = ["NONE", "#e00033", "#4a7d00", "#b65050", "#065fff", "#6052cf", "#1f77bb", "NONE"]

[colors.tab_bar]
inactive_tab_edge = "#b3b3b3"
background = "#ffffff"

[colors.tab_bar.active_tab]
fg_color = "#ffffff"
bg_color = "#397a70"

[colors.tab_bar.inactive_tab]
fg_color = "#397a70"
bg_color = "#dbdbdb"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#397a70"
bg_color = "#e4efd8"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#217a3c"
bg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#3740cf"
bg_color = "#ffffff"

[metadata]
aliases = []
author = "prot"
name = "ef-light"