[colors]
foreground = "#151a27"
background = "#edf4f8"
cursor_bg = "#036f99"
cursor_border = "#036f99"
cursor_fg = "#edf4f8"
selection_bg = "#c8dcff"
selection_fg = "#151a27"
split = "#a2a6af"
compose_cursor = "#805a1f"
scrollbar_thumb = "#dae5f0"

ansi = ["#151a27", "#c3303a", "#007010", "#805a1f", "#375cc6", "#80308f", "#1f66af", "#afb8c3"]
brights = ["#676470", "#d00000", "#3a6f00", "#8b4400", "#444fcf", "#9a3a6a", "#305675", "#edf4f8"]

[colors.tab_bar]
inactive_tab_edge = "#dbe4e6"
background = "#edf4f8"

[colors.tab_bar.active_tab]
fg_color = "#edf4f8"
bg_color = "#3f4f99"

[colors.tab_bar.inactive_tab]
fg_color = "#3f4f99"
bg_color = "#e0e7ef"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#3f4f99"
bg_color = "#dae5f0"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#007010"
bg_color = "#edf4f8"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#375cc6"
bg_color = "#edf4f8"

[metadata]
aliases = []
author = "prot"
name = "ef-maris-light"