[colors]
foreground = "#eaedef"
background = "#131c2b"
cursor_bg = "#8fdfff"
cursor_border = "#8fdfff"
cursor_fg = "#131c2b"
selection_bg = "#183c65"
selection_fg = "#eaedef"
split = "#595a63"
compose_cursor = "#d0d24f"
scrollbar_thumb = "#243242"

ansi = ["black", "#ff6f6f", "#41bf4f", "#d0d24f", "#57b0ff", "#f59acf", "#2fd0db", "gray65"]
brights = ["gray35", "#ff7788", "#7fce5f", "#f0c060", "#70a0ff", "#cf90ff", "#65d5a8", "white"]

[colors.tab_bar]
inactive_tab_edge = "#4a5664"
background = "#131c2b"

[colors.tab_bar.active_tab]
fg_color = "#131c2b"
bg_color = "#90a0dc"

[colors.tab_bar.inactive_tab]
fg_color = "#90a0dc"
bg_color = "#2a3644"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#90a0dc"
bg_color = "#243242"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#41bf4f"
bg_color = "#131c2b"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#57b0ff"
bg_color = "#131c2b"

[metadata]
aliases = []
author = "prot"
name = "ef-maris-dark"