[colors]
foreground = "#d0d0d0"
background = "#292c2f"
cursor_bg = "#afe6ef"
cursor_border = "#afe6ef"
cursor_fg = "#292c2f"
selection_bg = "#404f66"
selection_fg = "#d0d0d0"
split = "#4f5f66"
compose_cursor = "#c09f6f"
scrollbar_thumb = "#344255"

ansi = ["#292c2f", "#d67869", "#70bb70", "#c09f6f", "#80a4e0", "#e5a0ea", "#8fb8ea", "#857f8f"]
brights = ["#60676b", "#df885f", "#98c06f", "#d1a45f", "#a0a0ef", "#d389af", "#99bfd0", "#d0d0d0"]

[colors.tab_bar]
inactive_tab_edge = "#3f3f46"
background = "#292c2f"

[colors.tab_bar.active_tab]
fg_color = "#292c2f"
bg_color = "#aab9af"

[colors.tab_bar.inactive_tab]
fg_color = "#aab9af"
bg_color = "#373b3d"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#aab9af"
bg_color = "#344255"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#70bb70"
bg_color = "#292c2f"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#80a4e0"
bg_color = "#292c2f"

[metadata]
aliases = []
author = "prot"
name = "ef-owl"