[colors]
foreground = "#4f204f"
background = "#f3eddf"
cursor_bg = "#9d5744"
cursor_border = "#9d5744"
cursor_fg = "#f3eddf"
selection_bg = "#e0d0ba"
selection_fg = "#4f204f"
split = "#c5afb6"
compose_cursor = "#87591f"
scrollbar_thumb = "#e7d9e0"

ansi = ["#4f204f", "#ba2d2f", "#007a0a", "#87591f", "#375cc6", "#9f4e74", "#3060af", "#b9aaa8"]
brights = ["#6f6877", "#b21f00", "#5a7400", "#a05900", "#5059c0", "#a73080", "#4f60a0", "#f3eddf"]

[colors.tab_bar]
inactive_tab_edge = "#e4dad7"
background = "#f3eddf"

[colors.tab_bar.active_tab]
fg_color = "#f3eddf"
bg_color = "#55447f"

[colors.tab_bar.inactive_tab]
fg_color = "#55447f"
bg_color = "#e5d6d4"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#55447f"
bg_color = "#e7d9e0"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#007a0a"
bg_color = "#f3eddf"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#375cc6"
bg_color = "#f3eddf"

[metadata]
aliases = []
author = "prot"
name = "ef-reverie"