[colors]
foreground = "#34494a"
background = "#f6fff9"
cursor_bg = "#bf005f"
cursor_border = "#bf005f"
cursor_fg = "#f6fff9"
selection_bg = "#d0e6ff"
selection_fg = "#34494a"
split = "#b4c4c0"
compose_cursor = "#a45f22"
scrollbar_thumb = "#f9e0e5"

ansi = ["black", "#c42d2f", "#1a870f", "#b6540f", "#5f5fdf", "#d5206f", "#1f6fbf", "gray65"]
brights = ["gray35", "#cf2f4f", "#007f68", "#a45f22", "#265fbf", "#9435b4", "#0f7b8f", "white"]

[colors.tab_bar]
inactive_tab_edge = "#c0c6c3"
background = "#f6fff9"

[colors.tab_bar.active_tab]
fg_color = "#f6fff9"
bg_color = "#9d5e7a"

[colors.tab_bar.inactive_tab]
fg_color = "#9d5e7a"
bg_color = "#e0e6e3"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#9d5e7a"
bg_color = "#f9e0e5"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#1a870f"
bg_color = "#f6fff9"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#375cc6"
bg_color = "#f6fff9"

[metadata]
aliases = []
author = "prot"
name = "ef-spring"