[colors]
foreground = "#34494a"
background = "#f6fff9"
cursor_bg = "#bf005f"
cursor_border = "#bf005f"
cursor_fg = "#f6fff9"
selection_bg = "#d0e6ff"
selection_fg = "#34494a"
split = "#b4c4c0"
compose_cursor = "#a45f22"
scrollbar_thumb = "#f9e0e5"

ansi = ["#34494a", "#c42d2f", "#1a870f", "#a45f22", "#375cc6", "#d5206f", "#1f6fbf", "#c0c6c3"]
brights = ["#777294", "#d03003", "#4a7d00", "#b6540f", "#5f5fdf", "#cb26a0", "#3f6faf", "#f6fff9"]

[colors.tab_bar]
inactive_tab_edge = "#eaf0e9"
background = "#f6fff9"

[colors.tab_bar.active_tab]
fg_color = "#f6fff9"
bg_color = "#9d5e7a"

[colors.tab_bar.inactive_tab]
fg_color = "#9d5e7a"
bg_color = "#e8f0f0"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#9d5e7a"
bg_color = "#f9e0e5"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#1a870f"
bg_color = "#f6fff9"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#375cc6"
bg_color = "#f6fff9"

[metadata]
aliases = []
author = "prot"
name = "ef-spring"