[colors]
foreground = "#ffffff"
background = "#0d0e1c"
cursor_bg = "#ff66ff"
cursor_border = "#ff66ff"
cursor_fg = "#0d0e1c"
selection_bg = "#555a66"
selection_fg = "#ffffff"
split = "#61647a"
compose_cursor = "#d0bc00"
scrollbar_thumb = "#303a6f"

ansi = ["#0d0e1c", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "#989898"]
brights = ["#4a4f69", "#ff6b55", "#70b900", "#fec43f", "#79a8ff", "#f78fe7", "#4ae2f0", "#ffffff"]

[colors.tab_bar]
inactive_tab_edge = "#2b3045"
background = "#0d0e1c"

[colors.tab_bar.active_tab]
fg_color = "#0d0e1c"
bg_color = "#c6daff"

[colors.tab_bar.inactive_tab]
fg_color = "#c6daff"
bg_color = "#1d2235"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c6daff"
bg_color = "#303a6f"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#44bc44"
bg_color = "#0d0e1c"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#2fafff"
bg_color = "#0d0e1c"

[metadata]
aliases = []
author = "prot"
name = "ef-tint"