[colors]
foreground = "#eeffff"
background = "#292d3e"
cursor_bg = "#ff66ff"
cursor_border = "#ff66ff"
cursor_fg = "#292d3e"
selection_bg = "#555a66"
selection_fg = "#eeffff"
split = "#61647a"
compose_cursor = "#d0bc00"
scrollbar_thumb = "#303a6f"

ansi = ["NONE", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "NONE"]
brights = ["NONE", "#ff6b55", "#70b900", "#fec43f", "#79a8ff", "#b6a0ff", "#6ae4b9", "NONE"]

[colors.tab_bar]
inactive_tab_edge = "#4a4f6a"
background = "#292d3e"

[colors.tab_bar.active_tab]
fg_color = "#0d0e1c"
bg_color = "#c6daff"

[colors.tab_bar.inactive_tab]
fg_color = "#c6daff"
bg_color = "#2c3045"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c6daff"
bg_color = "#303a6f"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#44bc44"
bg_color = "#292d3e"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#2fafff"
bg_color = "#292d3e"

[metadata]
aliases = []
author = "prot"
name = "ef-tint"