[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#808f80", italic = true }

# Hovered
hovered         = { bg = "#00331f" }
preview_hovered = { bg = "#00331f" }

# Find
find_keyword  = { fg = "#222522", bg = "#3b3400", bold = true }
find_position = { fg = "#222522", bg = "#4648d0", bold = true }

# Marker
marker_copied   = { fg = "#3fb83f", bg = "#3fb83f" }
marker_cut      = { fg = "#ef6560", bg = "#ef6560" }
marker_marked   = { fg = "#d38faf", bg = "#d38faf" }
marker_selected = { fg = "#37aff6", bg = "#37aff6" }

# Tab
tab_active   = { fg = "#cfdfd5", bg = "#303230" }
tab_inactive = { fg = "#808f80", bg = "#505250" }
tab_width    = 1

# Count
count_copied   = { fg = "#cfdfd5", bg = "#7fc07f" }
count_cut      = { fg = "#cfdfd5", bg = "#f47360" }
count_selected = { fg = "#cfdfd5", bg = "#37aff6" }

# Border
border_symbol = "│"
border_style  = { fg = "#525959" }

[mode]
normal_main = { fg = "black", bg = "#37aff6", bold = true }
normal_alt  = { fg = "#37aff6", bg = "#808f80" }

select_main = { fg = "black", bg = "#d38faf", bold = true }
select_alt  = { fg = "#d38faf", bg = "#808f80" }

unset_main  = { fg = "black", bg = "#af9fff", bold = true }
unset_alt   = { fg = "#af9fff", bg = "#808f80" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#808f80", bg = "#808f80" }

# Progress
progress_label  = { fg = "#808f80", bold = true }
progress_normal = { fg = "#111111" }
progress_error  = { fg = "#ef6560" }

# Permissions
perm_type  = { fg = "#37aff6" }
perm_read  = { fg = "#d4aa02" }
perm_write = { fg = "#ef6560" }
perm_exec  = { fg = "#3fb83f" }
perm_sep   = { fg = "black" }

[pick]
border   = { fg = "#525959" }
active   = { fg = "#cfdfd5",  bg = "#00331f" }
inactive = { fg = "#8fcfaf" }

# Input
[input]
border   = { fg = "#6ab4cf" }
title    = { fg = "#6ab4cf" }
value    = { fg = "#af9fff" }
selected = { bg = "#00331f" }

# Completion
[completion]
border   = { fg = "#6ab4cf" }
active   = { fg = "#cfdfd5", bg = "#00331f" }
inactive = { fg = "#cfdfd5" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#525959" }
title   = { fg = "#525959" }
hovered = { fg = "#cfdfd5", bg="#00331f" }

# Which
[which]
cols            = 3
mask            = { bg = "#222522" }
cand            = { fg = "#6fc5ef" }
rest            = { fg = "#37aff6" }
desc            = { fg = "#d38faf" }
separator       = " ➜ "
separator_style = { fg = "#b7a07f" }

# Confirm
[confirm]
border  = { fg = "#6ab4cf" }
title   = { fg = "#525959" }
content = {}
list    = {}
btn_yes = { bg = "#00331f" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#525959" }
title   = { fg = "#525959" }

# Notify
[notify]
title_info  = { fg = "#3fb83f" }
title_warn  = { fg = "#cfc04f" }
title_error = { fg = "#ef6560" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#3fb83f" }
run     = { fg = "#d38faf" }
hovered = { bg = "#00331f" }
footer  = { fg = "#cfdfd5", bg = "#111111" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#d4aa02" },

	# Media
	{ mime = "{audio,video}/*", fg = "#d38faf" },

	# Archives
	{ mime = "application/*zip", fg = "#ef6560" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ef6560" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6fc5ef" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ef6560" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ef6560" },
	{ name = "*", is = "exec"  , fg = "#3fb83f" },

	# Fallback
	{ name = "*/", fg = "#37aff6" }
]
    