[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#676470", italic = true }

# Hovered
hovered         = { bg = "#d0e7c4" }
preview_hovered = { bg = "#d0e7c4" }

# Find
find_keyword  = { fg = "#e3e9d6", bg = "#e8e8aa", bold = true }
find_position = { fg = "#e3e9d6", bg = "#cfceff", bold = true }

# Marker
marker_copied   = { fg = "#00601f", bg = "#00601f" }
marker_cut      = { fg = "#c3303a", bg = "#c3303a" }
marker_marked   = { fg = "#80308f", bg = "#80308f" }
marker_selected = { fg = "#375cc6", bg = "#375cc6" }

# Tab
tab_active   = { fg = "#221321", bg = "#d0d7ca" }
tab_inactive = { fg = "#676470", bg = "#b0b7aa" }
tab_width    = 1

# Count
count_copied   = { fg = "#221321", bg = "#306630" }
count_cut      = { fg = "#221321", bg = "#d00000" }
count_selected = { fg = "#221321", bg = "#375cc6" }

# Border
border_symbol = "│"
border_style  = { fg = "#a5aaaf" }

[mode]
normal_main = { fg = "black", bg = "#375cc6", bold = true }
normal_alt  = { fg = "#375cc6", bg = "#676470" }

select_main = { fg = "${black}", bg = "#80308f", bold = true }
select_alt  = { fg = "#80308f", bg = "#676470" }

unset_main  = { fg = "black", bg = "#5032aa", bold = true }
unset_alt   = { fg = "#5032aa", bg = "#676470" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#676470", bg = "#676470" }

# Progress
progress_label  = { fg = "#676470", bold = true }
progress_normal = { fg = "#edf5e2" }
progress_error  = { fg = "#d00000" }

# Permissions
perm_type  = { fg = "#375cc6" }
perm_read  = { fg = "#9a501f" }
perm_write = { fg = "#c3303a" }
perm_exec  = { fg = "#00601f" }
perm_sep   = { fg = "black" }

[pick]
border   = { fg = "#a5aaaf" }
active   = { fg = "#221321",  bg = "#d0e7c4" }
inactive = { fg = "#5f5f1f" }

# Input
[input]
border   = { fg = "#3a5099" }
title    = { fg = "#3a5099" }
value    = { fg = "#5032aa" }
selected = { bg = "#d0e7c4" }

# Completion
[completion]
border   = { fg = "#3a5099" }
active   = { fg = "#221321", bg = "#d0e7c4" }
inactive = { fg = "#221321" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#a5aaaf" }
title   = { fg = "#a5aaaf" }
hovered = { fg = "#221321", bg="#d0e7c4" }

# Which
[which]
cols            = 3
mask            = { bg = "#e3e9d6" }
cand            = { fg = "#1f70af" }
rest            = { fg = "#375cc6" }
desc            = { fg = "#80308f" }
separator       = " ➜ "
separator_style = { fg = "#7f4f4a" }

# Confirm
[confirm]
border  = { fg = "#3a5099" }
title   = { fg = "#a5aaaf" }
content = {}
list    = {}
btn_yes = { bg = "#d0e7c4" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#a5aaaf" }
title   = { fg = "#a5aaaf" }

# Notify
[notify]
title_info  = { fg = "#007047" }
title_warn  = { fg = "#b04300" }
title_error = { fg = "#d00000" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#00601f" }
run     = { fg = "#80308f" }
hovered = { bg = "${bg_highlight}" }
footer  = { fg = "#221321", bg = "#edf5e2" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#9a501f" },

	# Media
	{ mime = "{audio,video}/*", fg = "#80308f" },

	# Archives
	{ mime = "application/*zip", fg = "#c3303a" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c3303a" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#1f70af" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#c3303a" },

	# Special files
	{ name = "*", is = "orphan", bg = "#c3303a" },
	{ name = "*", is = "exec"  , fg = "#00601f" },

	# Fallback
	{ name = "*/", fg = "#375cc6" }
]
    