[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#66657f", italic = true }

# Hovered
hovered         = { bg = "#dff6e4" }
preview_hovered = { bg = "#dff6e4" }

# Find
find_keyword  = { fg = "#eaefef", bg = "#ffe9bf", bold = true }
find_position = { fg = "#eaefef", bg = "#cbcfff", bold = true }

# Marker
marker_copied   = { fg = "#008a00", bg = "#008a00" }
marker_cut      = { fg = "#c42d2f", bg = "#c42d2f" }
marker_marked   = { fg = "#aa44c5", bg = "#aa44c5" }
marker_selected = { fg = "#004fc0", bg = "#004fc0" }

# Tab
tab_active   = { fg = "#232323", bg = "#d7dbdb" }
tab_inactive = { fg = "#66657f", bg = "#b5b8b8" }
tab_width    = 1

# Count
count_copied   = { fg = "#232323", bg = "#517f3c" }
count_cut      = { fg = "#232323", bg = "#d03003" }
count_selected = { fg = "#232323", bg = "#004fc0" }

# Border
border_symbol = "│"
border_style  = { fg = "#b0b7c0" }

[mode]
normal_main = { fg = "NONE", bg = "#004fc0", bold = true }
normal_alt  = { fg = "#004fc0", bg = "#66657f" }

select_main = { fg = "NONE", bg = "#aa44c5", bold = true }
select_alt  = { fg = "#aa44c5", bg = "#66657f" }

unset_main  = { fg = "NONE", bg = "#7f5ae0", bold = true }
unset_alt   = { fg = "#7f5ae0", bg = "#66657f" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#66657f", bg = "#66657f" }

# Progress
progress_label  = { fg = "#66657f", bold = true }
progress_normal = { fg = "#fcffff" }
progress_error  = { fg = "#c42d2f" }

# Permissions
perm_type  = { fg = "#004fc0" }
perm_read  = { fg = "#aa6100" }
perm_write = { fg = "#c42d2f" }
perm_exec  = { fg = "#008a00" }
perm_sep   = { fg = "NONE" }

[pick]
border   = { fg = "#b0b7c0" }
active   = { fg = "#232323",  bg = "#dff6e4" }
inactive = { fg = "#204f9a" }

# Input
[input]
border   = { fg = "#375cc8" }
title    = { fg = "#375cc8" }
value    = { fg = "#7f5ae0" }
selected = { bg = "#dff6e4" }

# Completion
[completion]
border   = { fg = "#375cc8" }
active   = { fg = "#232323", bg = "#dff6e4" }
inactive = { fg = "#232323" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#b0b7c0" }
title   = { fg = "#b0b7c0" }
hovered = { fg = "#232323", bg="#dff6e4" }

# Which
[which]
cols            = 3
mask            = { bg = "#eaefef" }
cand            = { fg = "#1f6fbf" }
rest            = { fg = "#004fc0" }
desc            = { fg = "#aa44c5" }
separator       = " ➜ "
separator_style = { fg = "#7a5f2f" }

# Confirm
[confirm]
border  = { fg = "#375cc8" }
title   = { fg = "#b0b7c0" }
content = {}
list    = {}
btn_yes = { bg = "#dff6e4" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#b0b7c0" }
title   = { fg = "#b0b7c0" }

# Notify
[notify]
title_info  = { fg = "#008a00" }
title_warn  = { fg = "#996c4f" }
title_error = { fg = "#c42d2f" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#008a00" }
run     = { fg = "#aa44c5" }
hovered = { bg = "#dff6e4" }
footer  = { fg = "#232323", bg = "#fcffff" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#aa6100" },

	# Media
	{ mime = "{audio,video}/*", fg = "#aa44c5" },

	# Archives
	{ mime = "application/*zip", fg = "#c42d2f" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c42d2f" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#1f6fbf" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#c42d2f" },

	# Special files
	{ name = "*", is = "orphan", bg = "#c42d2f" },
	{ name = "*", is = "exec"  , fg = "#008a00" },

	# Fallback
	{ name = "*/", fg = "#004fc0" }
]
    