[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#776f79", italic = true }

# Hovered
hovered         = { bg = "#f2e5d9" }
preview_hovered = { bg = "#f2e5d9" }

# Find
find_keyword  = { fg = "#efe7e7", bg = "#ffe0aa", bold = true }
find_position = { fg = "#efe7e7", bg = "#cbcfff", bold = true }

# Marker
marker_copied   = { fg = "#217a3c", bg = "#217a3c" }
marker_cut      = { fg = "#b00234", bg = "#b00234" }
marker_marked   = { fg = "#a01f64", bg = "#a01f64" }
marker_selected = { fg = "#3c3bbe", bg = "#3c3bbe" }

# Tab
tab_active   = { fg = "#201f36", bg = "#e0dbdb" }
tab_inactive = { fg = "#776f79", bg = "#c0bbbb" }
tab_width    = 1

# Count
count_copied   = { fg = "#201f36", bg = "#61756c" }
count_cut      = { fg = "#201f36", bg = "#e00033" }
count_selected = { fg = "#201f36", bg = "#3c3bbe" }

# Border
border_symbol = "│"
border_style  = { fg = "#bab7bc" }

[mode]
normal_main = { fg = "NONE", bg = "#3c3bbe", bold = true }
normal_alt  = { fg = "#3c3bbe", bg = "#776f79" }

select_main = { fg = "NONE", bg = "#a01f64", bold = true }
select_alt  = { fg = "#a01f64", bg = "#776f79" }

unset_main  = { fg = "NONE", bg = "#7022bf", bold = true }
unset_alt   = { fg = "#7022bf", bg = "#776f79" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#776f79", bg = "#776f79" }

# Progress
progress_label  = { fg = "#776f79", bold = true }
progress_normal = { fg = "#fff7f7" }
progress_error  = { fg = "#e00033" }

# Permissions
perm_type  = { fg = "#3c3bbe" }
perm_read  = { fg = "#9a6012" }
perm_write = { fg = "#b00234" }
perm_exec  = { fg = "#217a3c" }
perm_sep   = { fg = "NONE" }

[pick]
border   = { fg = "#bab7bc" }
active   = { fg = "#201f36",  bg = "#f2e5d9" }
inactive = { fg = "#af4988" }

# Input
[input]
border   = { fg = "#6060d0" }
title    = { fg = "#6060d0" }
value    = { fg = "#7022bf" }
selected = { bg = "#f2e5d9" }

# Completion
[completion]
border   = { fg = "#6060d0" }
active   = { fg = "#201f36", bg = "#f2e5d9" }
inactive = { fg = "#201f36" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#bab7bc" }
title   = { fg = "#bab7bc" }
hovered = { fg = "#201f36", bg="#f2e5d9" }

# Which
[which]
cols            = 3
mask            = { bg = "#efe7e7" }
cand            = { fg = "#2f5f9f" }
rest            = { fg = "#3c3bbe" }
desc            = { fg = "#a01f64" }
separator       = " ➜ "
separator_style = { fg = "#506fa0" }

# Confirm
[confirm]
border  = { fg = "#6060d0" }
title   = { fg = "#bab7bc" }
content = {}
list    = {}
btn_yes = { bg = "#f2e5d9" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#bab7bc" }
title   = { fg = "#bab7bc" }

# Notify
[notify]
title_info  = { fg = "#217a3c" }
title_warn  = { fg = "#b6530f" }
title_error = { fg = "#e00033" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#217a3c" }
run     = { fg = "#a01f64" }
hovered = { bg = "#f2e5d9" }
footer  = { fg = "#201f36", bg = "#fff7f7" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#9a6012" },

	# Media
	{ mime = "{audio,video}/*", fg = "#a01f64" },

	# Archives
	{ mime = "application/*zip", fg = "#b00234" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#b00234" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#2f5f9f" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#b00234" },

	# Special files
	{ name = "*", is = "orphan", bg = "#b00234" },
	{ name = "*", is = "exec"  , fg = "#217a3c" },

	# Fallback
	{ name = "*/", fg = "#3c3bbe" }
]
    