[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#969faf", italic = true }

# Hovered
hovered         = { bg = "#243242" }
preview_hovered = { bg = "#243242" }

# Find
find_keyword  = { fg = "#1d2c39", bg = "#403f22", bold = true }
find_position = { fg = "#1d2c39", bg = "#2f5f9f", bold = true }

# Marker
marker_copied   = { fg = "#41bf4f", bg = "#41bf4f" }
marker_cut      = { fg = "#ff6f6f", bg = "#ff6f6f" }
marker_marked   = { fg = "#f59acf", bg = "#f59acf" }
marker_selected = { fg = "#57b0ff", bg = "#57b0ff" }

# Tab
tab_active   = { fg = "#eaedef", bg = "#2a3644" }
tab_inactive = { fg = "#969faf", bg = "#4a5664" }
tab_width    = 1

# Count
count_copied   = { fg = "#eaedef", bg = "#a9c99f" }
count_cut      = { fg = "#eaedef", bg = "#ff7a5f" }
count_selected = { fg = "#eaedef", bg = "#57b0ff" }

# Border
border_symbol = "│"
border_style  = { fg = "#595a63" }

[mode]
normal_main = { fg = "NONE", bg = "#57b0ff", bold = true }
normal_alt  = { fg = "#57b0ff", bg = "#969faf" }

select_main = { fg = "NONE", bg = "#f59acf", bold = true }
select_alt  = { fg = "#f59acf", bg = "#969faf" }

unset_main  = { fg = "NONE", bg = "#cf90ff", bold = true }
unset_alt   = { fg = "#cf90ff", bg = "#969faf" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#969faf", bg = "#969faf" }

# Progress
progress_label  = { fg = "#969faf", bold = true }
progress_normal = { fg = "#131c2b" }
progress_error  = { fg = "#ff7a5f" }

# Permissions
perm_type  = { fg = "#57b0ff" }
perm_read  = { fg = "#d0d24f" }
perm_write = { fg = "#ff6f6f" }
perm_exec  = { fg = "#41bf4f" }
perm_sep   = { fg = "NONE" }

[pick]
border   = { fg = "#595a63" }
active   = { fg = "#eaedef",  bg = "#243242" }
inactive = { fg = "#90a0dc" }

# Input
[input]
border   = { fg = "#9acfff" }
title    = { fg = "#9acfff" }
value    = { fg = "#cf90ff" }
selected = { bg = "#243242" }

# Completion
[completion]
border   = { fg = "#9acfff" }
active   = { fg = "#eaedef", bg = "#243242" }
inactive = { fg = "#eaedef" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#595a63" }
title   = { fg = "#595a63" }
hovered = { fg = "#eaedef", bg="#243242" }

# Which
[which]
cols            = 3
mask            = { bg = "#1d2c39" }
cand            = { fg = "#2fd0db" }
rest            = { fg = "#57b0ff" }
desc            = { fg = "#f59acf" }
separator       = " ➜ "
separator_style = { fg = "#eaa4a4" }

# Confirm
[confirm]
border  = { fg = "#9acfff" }
title   = { fg = "#595a63" }
content = {}
list    = {}
btn_yes = { bg = "#243242" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#595a63" }
title   = { fg = "#595a63" }

# Notify
[notify]
title_info  = { fg = "#30c489" }
title_warn  = { fg = "#f0c060" }
title_error = { fg = "#ff7a5f" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#41bf4f" }
run     = { fg = "#f59acf" }
hovered = { bg = "#243242" }
footer  = { fg = "#eaedef", bg = "#131c2b" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#d0d24f" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f59acf" },

	# Archives
	{ mime = "application/*zip", fg = "#ff6f6f" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff6f6f" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#2fd0db" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ff6f6f" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff6f6f" },
	{ name = "*", is = "exec"  , fg = "#41bf4f" },

	# Fallback
	{ name = "*/", fg = "#57b0ff" }
]
    