[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#777294", italic = true }

# Hovered
hovered         = { bg = "#f9e0e5" }
preview_hovered = { bg = "#f9e0e5" }

# Find
find_keyword  = { fg = "#e8f0f0", bg = "#ffecba", bold = true }
find_position = { fg = "#e8f0f0", bg = "#afdfff", bold = true }

# Marker
marker_copied   = { fg = "#1a870f", bg = "#1a870f" }
marker_cut      = { fg = "#c42d2f", bg = "#c42d2f" }
marker_marked   = { fg = "#d5206f", bg = "#d5206f" }
marker_selected = { fg = "#375cc6", bg = "#375cc6" }

# Tab
tab_active   = { fg = "#34494a", bg = "#e0e6e3" }
tab_inactive = { fg = "#777294", bg = "#c0c6c3" }
tab_width    = 1

# Count
count_copied   = { fg = "#34494a", bg = "#61756c" }
count_cut      = { fg = "#34494a", bg = "#d03003" }
count_selected = { fg = "#34494a", bg = "#375cc6" }

# Border
border_symbol = "│"
border_style  = { fg = "#b4c4c0" }

[mode]
normal_main = { fg = "NONE", bg = "#375cc6", bold = true }
normal_alt  = { fg = "#375cc6", bg = "#777294" }

select_main = { fg = "NONE", bg = "#d5206f", bold = true }
select_alt  = { fg = "#d5206f", bg = "#777294" }

unset_main  = { fg = "NONE", bg = "#9435b4", bold = true }
unset_alt   = { fg = "#9435b4", bg = "#777294" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#777294", bg = "#777294" }

# Progress
progress_label  = { fg = "#777294", bold = true }
progress_normal = { fg = "#f6fff9" }
progress_error  = { fg = "#d03003" }

# Permissions
perm_type  = { fg = "#375cc6" }
perm_read  = { fg = "#a45f22" }
perm_write = { fg = "#c42d2f" }
perm_exec  = { fg = "#1a870f" }
perm_sep   = { fg = "NONE" }

[pick]
border   = { fg = "#b4c4c0" }
active   = { fg = "#34494a",  bg = "#f9e0e5" }
inactive = { fg = "#9d5e7a" }

# Input
[input]
border   = { fg = "#6a65bf" }
title    = { fg = "#6a65bf" }
value    = { fg = "#9435b4" }
selected = { bg = "#f9e0e5" }

# Completion
[completion]
border   = { fg = "#6a65bf" }
active   = { fg = "#34494a", bg = "#f9e0e5" }
inactive = { fg = "#34494a" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#b4c4c0" }
title   = { fg = "#b4c4c0" }
hovered = { fg = "#34494a", bg="#f9e0e5" }

# Which
[which]
cols            = 3
mask            = { bg = "#e8f0f0" }
cand            = { fg = "#1f6fbf" }
rest            = { fg = "#375cc6" }
desc            = { fg = "#d5206f" }
separator       = " ➜ "
separator_style = { fg = "#876450" }

# Confirm
[confirm]
border  = { fg = "#6a65bf" }
title   = { fg = "#b4c4c0" }
content = {}
list    = {}
btn_yes = { bg = "#f9e0e5" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#b4c4c0" }
title   = { fg = "#b4c4c0" }

# Notify
[notify]
title_info  = { fg = "#1a870f" }
title_warn  = { fg = "#a45f22" }
title_error = { fg = "#d03003" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#1a870f" }
run     = { fg = "#d5206f" }
hovered = { bg = "#f9e0e5" }
footer  = { fg = "#34494a", bg = "#f6fff9" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#a45f22" },

	# Media
	{ mime = "{audio,video}/*", fg = "#d5206f" },

	# Archives
	{ mime = "application/*zip", fg = "#c42d2f" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c42d2f" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#1f6fbf" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#c42d2f" },

	# Special files
	{ name = "*", is = "orphan", bg = "#c42d2f" },
	{ name = "*", is = "exec"  , fg = "#1a870f" },

	# Fallback
	{ name = "*/", fg = "#375cc6" }
]
    