[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#908890", italic = true }

# Hovered
hovered         = { bg = "#34223f" }
preview_hovered = { bg = "#34223f" }

# Find
find_keyword  = { fg = "#2a2228", bg = "#3a330f", bold = true }
find_position = { fg = "#2a2228", bg = "#4648d0", bold = true }

# Marker
marker_copied   = { fg = "#60b444", bg = "#60b444" }
marker_cut      = { fg = "#f48359", bg = "#f48359" }
marker_marked   = { fg = "#d37faf", bg = "#d37faf" }
marker_selected = { fg = "#7fa5f6", bg = "#7fa5f6" }

# Tab
tab_active   = { fg = "#d8cfd5", bg = "#362f35" }
tab_inactive = { fg = "#908890", bg = "#564f55" }
tab_width    = 1

# Count
count_copied   = { fg = "#d8cfd5", bg = "#61a06c" }
count_cut      = { fg = "#d8cfd5", bg = "#ff7560" }
count_selected = { fg = "#d8cfd5", bg = "#7fa5f6" }

# Border
border_symbol = "│"
border_style  = { fg = "#605760" }

[mode]
normal_main = { fg = "NONE", bg = "#7fa5f6", bold = true }
normal_alt  = { fg = "#7fa5f6", bg = "#908890" }

select_main = { fg = "NONE", bg = "#d37faf", bold = true }
select_alt  = { fg = "#d37faf", bg = "#908890" }

unset_main  = { fg = "NONE", bg = "#a698ef", bold = true }
unset_alt   = { fg = "#a698ef", bg = "#908890" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#908890", bg = "#908890" }

# Progress
progress_label  = { fg = "#908890", bold = true }
progress_normal = { fg = "#160f0f" }
progress_error  = { fg = "#ff7560" }

# Permissions
perm_type  = { fg = "#7fa5f6" }
perm_read  = { fg = "#d4a052" }
perm_write = { fg = "#f48359" }
perm_exec  = { fg = "#60b444" }
perm_sep   = { fg = "NONE" }

[pick]
border   = { fg = "#605760" }
active   = { fg = "#d8cfd5",  bg = "#34223f" }
inactive = { fg = "#afdacf" }

# Input
[input]
border   = { fg = "#7a94df" }
title    = { fg = "#7a94df" }
value    = { fg = "#a698ef" }
selected = { bg = "#34223f" }

# Completion
[completion]
border   = { fg = "#7a94df" }
active   = { fg = "#d8cfd5", bg = "#34223f" }
inactive = { fg = "#d8cfd5" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#605760" }
title   = { fg = "#605760" }
hovered = { fg = "#d8cfd5", bg="#34223f" }

# Which
[which]
cols            = 3
mask            = { bg = "#2a2228" }
cand            = { fg = "#8fbaff" }
rest            = { fg = "#7fa5f6" }
desc            = { fg = "#d37faf" }
separator       = " ➜ "
separator_style = { fg = "#c7a07f" }

# Confirm
[confirm]
border  = { fg = "#7a94df" }
title   = { fg = "#605760" }
content = {}
list    = {}
btn_yes = { bg = "#34223f" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#605760" }
title   = { fg = "#605760" }

# Notify
[notify]
title_info  = { fg = "#60b444" }
title_warn  = { fg = "#d4a052" }
title_error = { fg = "#ff7560" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#60b444" }
run     = { fg = "#d37faf" }
hovered = { bg = "#34223f" }
footer  = { fg = "#d8cfd5", bg = "#160f0f" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#d4a052" },

	# Media
	{ mime = "{audio,video}/*", fg = "#d37faf" },

	# Archives
	{ mime = "application/*zip", fg = "#f48359" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f48359" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#8fbaff" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f48359" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f48359" },
	{ name = "*", is = "exec"  , fg = "#60b444" },

	# Fallback
	{ name = "*/", fg = "#7fa5f6" }
]
    