[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#786e74", italic = true }

# Hovered
hovered         = { bg = "#cfe6ff" }
preview_hovered = { bg = "#cfe6ff" }

# Find
find_keyword  = { fg = "#ebe7f1", bg = "#ffe5bf", bold = true }
find_position = { fg = "#ebe7f1", bg = "#cbcfff", bold = true }

# Marker
marker_copied   = { fg = "#057800", bg = "#057800" }
marker_cut      = { fg = "#c3303a", bg = "#c3303a" }
marker_marked   = { fg = "#ad45ba", bg = "#ad45ba" }
marker_selected = { fg = "#375cd6", bg = "#375cd6" }

# Tab
tab_active   = { fg = "#4f3363", bg = "#e3e0e9" }
tab_inactive = { fg = "#786e74", bg = "#c3c0c9" }
tab_width    = 1

# Count
count_copied   = { fg = "#4f3363", bg = "#41754c" }
count_cut      = { fg = "#4f3363", bg = "#d03033" }
count_selected = { fg = "#4f3363", bg = "#375cd6" }

# Border
border_symbol = "│"
border_style  = { fg = "#c6bac5" }

[mode]
normal_main = { fg = "black", bg = "#375cd6", bold = true }
normal_alt  = { fg = "#375cd6", bg = "#786e74" }

select_main = { fg = "${black}", bg = "#ad45ba", bold = true }
select_alt  = { fg = "#ad45ba", bg = "#786e74" }

unset_main  = { fg = "black", bg = "#705ae3", bold = true }
unset_alt   = { fg = "#705ae3", bg = "#786e74" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#786e74", bg = "#786e74" }

# Progress
progress_label  = { fg = "#786e74", bold = true }
progress_normal = { fg = "#f8f5ff" }
progress_error  = { fg = "#d03033" }

# Permissions
perm_type  = { fg = "#375cd6" }
perm_read  = { fg = "#a45f22" }
perm_write = { fg = "#c3303a" }
perm_exec  = { fg = "#057800" }
perm_sep   = { fg = "black" }

[pick]
border   = { fg = "#c6bac5" }
active   = { fg = "#4f3363",  bg = "#cfe6ff" }
inactive = { fg = "#3f7668" }

# Input
[input]
border   = { fg = "#6060d0" }
title    = { fg = "#6060d0" }
value    = { fg = "#705ae3" }
selected = { bg = "#cfe6ff" }

# Completion
[completion]
border   = { fg = "#6060d0" }
active   = { fg = "#4f3363", bg = "#cfe6ff" }
inactive = { fg = "#4f3363" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#c6bac5" }
title   = { fg = "#c6bac5" }
hovered = { fg = "#4f3363", bg="#cfe6ff" }

# Which
[which]
cols            = 3
mask            = { bg = "#ebe7f1" }
cand            = { fg = "#1f6fbf" }
rest            = { fg = "#375cd6" }
desc            = { fg = "#ad45ba" }
separator       = " ➜ "
separator_style = { fg = "#a05b5f" }

# Confirm
[confirm]
border  = { fg = "#6060d0" }
title   = { fg = "#c6bac5" }
content = {}
list    = {}
btn_yes = { bg = "#cfe6ff" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#c6bac5" }
title   = { fg = "#c6bac5" }

# Notify
[notify]
title_info  = { fg = "#057800" }
title_warn  = { fg = "#b8532f" }
title_error = { fg = "#d03033" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#057800" }
run     = { fg = "#ad45ba" }
hovered = { bg = "${bg_highlight}" }
footer  = { fg = "#4f3363", bg = "#f8f5ff" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#a45f22" },

	# Media
	{ mime = "{audio,video}/*", fg = "#ad45ba" },

	# Archives
	{ mime = "application/*zip", fg = "#c3303a" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c3303a" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#1f6fbf" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#c3303a" },

	# Special files
	{ name = "*", is = "orphan", bg = "#c3303a" },
	{ name = "*", is = "exec"  , fg = "#057800" },

	# Fallback
	{ name = "*/", fg = "#375cd6" }
]
    