[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#70819f", italic = true }

# Hovered
hovered         = { bg = "#303a6f" }
preview_hovered = { bg = "#303a6f" }

# Find
find_keyword  = { fg = "#1a202b", bg = "#3b2f04", bold = true }
find_position = { fg = "#1a202b", bg = "#2277ae", bold = true }

# Marker
marker_copied   = { fg = "#44bc44", bg = "#44bc44" }
marker_cut      = { fg = "#ff5f59", bg = "#ff5f59" }
marker_marked   = { fg = "#feacd0", bg = "#feacd0" }
marker_selected = { fg = "#2fafff", bg = "#2fafff" }

# Tab
tab_active   = { fg = "#eeffff", bg = "#2c3045" }
tab_inactive = { fg = "#70819f", bg = "#4a4f6a" }
tab_width    = 1

# Count
count_copied   = { fg = "#eeffff", bg = "#88ca9f" }
count_cut      = { fg = "#eeffff", bg = "#ff6b55" }
count_selected = { fg = "#eeffff", bg = "#2fafff" }

# Border
border_symbol = "│"
border_style  = { fg = "#61647a" }

[mode]
normal_main = { fg = "NONE", bg = "#2fafff", bold = true }
normal_alt  = { fg = "#2fafff", bg = "#70819f" }

select_main = { fg = "NONE", bg = "#feacd0", bold = true }
select_alt  = { fg = "#feacd0", bg = "#70819f" }

unset_main  = { fg = "NONE", bg = "#b6a0ff", bold = true }
unset_alt   = { fg = "#b6a0ff", bg = "#70819f" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#70819f", bg = "#70819f" }

# Progress
progress_label  = { fg = "#70819f", bold = true }
progress_normal = { fg = "#292d3e" }
progress_error  = { fg = "#ff5f59" }

# Permissions
perm_type  = { fg = "#2fafff" }
perm_read  = { fg = "#d0bc00" }
perm_write = { fg = "#ff5f59" }
perm_exec  = { fg = "#44bc44" }
perm_sep   = { fg = "NONE" }

[pick]
border   = { fg = "#61647a" }
active   = { fg = "#eeffff",  bg = "#303a6f" }
inactive = { fg = "#c6daff" }

# Input
[input]
border   = { fg = "#82b0ec" }
title    = { fg = "#82b0ec" }
value    = { fg = "#b6a0ff" }
selected = { bg = "#303a6f" }

# Completion
[completion]
border   = { fg = "#82b0ec" }
active   = { fg = "#eeffff", bg = "#303a6f" }
inactive = { fg = "#eeffff" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#61647a" }
title   = { fg = "#61647a" }
hovered = { fg = "#eeffff", bg="#303a6f" }

# Which
[which]
cols            = 3
mask            = { bg = "#1a202b" }
cand            = { fg = "#00d3d0" }
rest            = { fg = "#2fafff" }
desc            = { fg = "#feacd0" }
separator       = " ➜ "
separator_style = { fg = "#ff8f80" }

# Confirm
[confirm]
border  = { fg = "#82b0ec" }
title   = { fg = "#61647a" }
content = {}
list    = {}
btn_yes = { bg = "#303a6f" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#61647a" }
title   = { fg = "#61647a" }

# Notify
[notify]
title_info  = { fg = "#00c06f" }
title_warn  = { fg = "#fec43f" }
title_error = { fg = "#ff5f59" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#44bc44" }
run     = { fg = "#feacd0" }
hovered = { bg = "#303a6f" }
footer  = { fg = "#eeffff", bg = "#292d3e" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#d0bc00" },

	# Media
	{ mime = "{audio,video}/*", fg = "#feacd0" },

	# Archives
	{ mime = "application/*zip", fg = "#ff5f59" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff5f59" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#00d3d0" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ff5f59" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff5f59" },
	{ name = "*", is = "exec"  , fg = "#44bc44" },

	# Fallback
	{ name = "*/", fg = "#2fafff" }
]
    