# vim:ft=kitty

## name: ef-autumn
## license: GNU
## author: Onam Hernandez


background #0f0e06
foreground #cfbcba
selection_background #302a3a
selection_foreground #cfbcba
url_color #00b066
cursor #cfbcba
cursor_text_color #0f0e06

# Tabs
active_tab_background #70a89f
active_tab_foreground #0f0e06
inactive_tab_background #26211d
inactive_tab_foreground #70a89f

# Windows
active_border_color #58514f
inactive_border_color #26211d

# normal
color0 #0f0e06
color1 #ef656a
color2 #2fa526
color3 #c48702
color4 #379cf6
color5 #d570af
color6 #4fb0cf
color7 #887c8a

# bright
color8  #56524f
color9  #f06a3f
color10 #64aa0f
color11 #d0730f
color12 #6a88ff
color13 #e580ea
color14 #6fafff
color15 #cfbcba

# extended colors
color16 #df8f6f
color17 #ff7a7f
  