# vim:ft=kitty

## name: ef-arcadia
## license: GNU
## author: Onam Hernandez


background #d6e4d3
foreground #40314e
selection_background #d0d0c0
selection_foreground #40314e
url_color #006e50
cursor #40314e
cursor_text_color #d6e4d3

# Tabs
active_tab_background #3f5f5f
active_tab_foreground #d6e4d3
inactive_tab_background #ced7c8
inactive_tab_foreground #3f5f5f

# Windows
active_border_color #959a9f
inactive_border_color #ced7c8

# normal
color0 #40314e
color1 #882000
color2 #206020
color3 #6b4500
color4 #113384
color5 #922e7f
color6 #125a7f
color7 #b0b7aa

# bright
color8  #646170
color9  #9a1500
color10 #3f6d00
color11 #743f00
color12 #3a40a0
color13 #960f4f
color14 #2a5090
color15 #d6e4d3

# extended colors
color16 #775228
color17 #800e38
  