# vim:ft=kitty

## name: ef-atlantis
## license: GNU
## author: Onam Hernandez


background #1a143e
foreground #bfcccf
selection_background #2b265b
selection_foreground #bfcccf
url_color #00a962
cursor #bfcccf
cursor_text_color #1a143e

# Tabs
active_tab_background #967e92
active_tab_foreground #1a143e
inactive_tab_background #1a204b
inactive_tab_foreground #967e92

# Windows
active_border_color #454e59
inactive_border_color #1a204b

# normal
color0 #1a143e
color1 #ef656a
color2 #1fa526
color3 #c48502
color4 #379cf6
color5 #d590af
color6 #4fb0cf
color7 #7f8385

# bright
color8  #3a4661
color9  #f47360
color10 #77b22f
color11 #e6832f
color12 #6a88ff
color13 #e580ea
color14 #6fafff
color15 #bfcccf

# extended colors
color16 #b5967b
color17 #ef798f
  