# vim:ft=kitty

## name: ef-duo-dark
## license: GNU
## author: Onam Hernandez


background #070019
foreground #d0d0d0
selection_background #301a4f
selection_foreground #d0d0d0
url_color #00b982
cursor #d0d0d0
cursor_text_color #070019

# Tabs
active_tab_background #89afef
active_tab_foreground #070019
inactive_tab_background #1d1a26
inactive_tab_foreground #89afef

# Windows
active_border_color #545f6f
inactive_border_color #1d1a26

# normal
color0 #070019
color1 #ef656a
color2 #1fa526
color3 #c48702
color4 #379cf6
color5 #d369af
color6 #5faaef
color7 #857f8f

# bright
color8  #4a4759
color9  #f47360
color10 #50a22f
color11 #d0730f
color12 #6f80ff
color13 #e580ea
color14 #7fafff
color15 #d0d0d0

# extended colors
color16 #df805f
color17 #ef798f
  