# vim:ft=kitty

## name: ef-dream
## license: GNU
## author: Onam Hernandez


background #232025
foreground #efd5c5
selection_background #412f4f
selection_foreground #efd5c5
url_color #3fc489
cursor #efd5c5
cursor_text_color #232025

# Tabs
active_tab_background #b0a0cf
active_tab_foreground #232025
inactive_tab_background #322f34
inactive_tab_foreground #b0a0cf

# Windows
active_border_color #635850
inactive_border_color #322f34

# normal
color0 #232025
color1 #ff6f6f
color2 #51b04f
color3 #c0b24f
color4 #57b0ff
color5 #ffaacf
color6 #6fb3c0
color7 #8f8886

# bright
color8  #5b595e
color9  #ff7a5f
color10 #7fce5f
color11 #d09950
color12 #80aadf
color13 #f498c0
color14 #8fcfd0
color15 #efd5c5

# extended colors
color16 #deb07a
color17 #e47980
  