# vim:ft=kitty

## name: ef-dark
## license: GNU
## author: Onam Hernandez


background #000000
foreground #d0d0d0
selection_background #002435
selection_foreground #d0d0d0
url_color #00a692
cursor #d0d0d0
cursor_text_color #000000

# Tabs
active_tab_background #89afef
active_tab_foreground #000000
inactive_tab_background #1a1a1a
inactive_tab_foreground #89afef

# Windows
active_border_color #4f4f5f
inactive_border_color #1a1a1a

# normal
color0 #000000
color1 #ef6560
color2 #0faa26
color3 #bf9032
color4 #3f95f6
color5 #d369af
color6 #4fbaef
color7 #857f8f

# bright
color8  #4b4b4b
color9  #f47360
color10 #6aad0f
color11 #d1843f
color12 #6a9fff
color13 #e580ea
color14 #6fafff
color15 #d0d0d0

# extended colors
color16 #df8a5a
color17 #ff5a7a
  