# vim:ft=kitty

## name: ef-eagle
## license: GNU
## author: Onam Hernandez


background #f1ecd0
foreground #231a1f
selection_background #ecdfba
selection_foreground #231a1f
url_color #006e50
cursor #231a1f
cursor_text_color #f1ecd0

# Tabs
active_tab_background #524874
active_tab_foreground #f1ecd0
inactive_tab_background #e4dbc0
inactive_tab_foreground #524874

# Windows
active_border_color #7f785f
inactive_border_color #e4dbc0

# normal
color0 #231a1f
color1 #882000
color2 #226022
color3 #6b4500
color4 #113384
color5 #822478
color6 #125a7f
color7 #aea88e

# bright
color8  #685f53
color9  #9a0000
color10 #3a7800
color11 #843300
color12 #3a3da0
color13 #960f4f
color14 #4a5d90
color15 #f1ecd0

# extended colors
color16 #775228
color17 #8f0038
  