# vim:ft=kitty

## name: ef-elea-dark
## license: GNU
## author: Onam Hernandez


background #222524
foreground #eaf2ef
selection_background #2f413f
selection_foreground #eaf2ef
url_color #50cf89
cursor #eaf2ef
cursor_text_color #222524

# Tabs
active_tab_background #8fcfbb
active_tab_foreground #222524
inactive_tab_background #303332
inactive_tab_foreground #8fcfbb

# Windows
active_border_color #5d5f63
inactive_border_color #303332

# normal
color0 #222524
color1 #ff656a
color2 #7fc87f
color3 #cac85f
color4 #57aff6
color5 #f59acf
color6 #6fcfd2
color7 #969faf

# bright
color8  #5e6160
color9  #ff7a5f
color10 #7fca5a
color11 #e0b02f
color12 #78afff
color13 #fa90ea
color14 #7fcfdf
color15 #eaf2ef

# extended colors
color16 #cfb27f
color17 #fa7f88
  