# vim:ft=kitty

## name: ef-fig
## license: GNU
## author: Onam Hernandez


background #3b2043
foreground #e4d3e1
selection_background #47275f
selection_foreground #e4d3e1
url_color #79d081
cursor #e4d3e1
cursor_text_color #3b2043

# Tabs
active_tab_background #c6a4cf
active_tab_foreground #3b2043
inactive_tab_background #432e4e
inactive_tab_foreground #c6a4cf

# Windows
active_border_color #796f6e
inactive_border_color #432e4e

# normal
color0 #3b2043
color1 #ef797f
color2 #7fbb3f
color3 #e4c53f
color4 #57aff6
color5 #ffb2d6
color6 #5fc0dc
color7 #9d9d9d

# bright
color8  #6a586e
color9  #ff7f5f
color10 #aad05a
color11 #f2a85f
color12 #78b2ff
color13 #f28fdf
color14 #7fc5df
color15 #e4d3e1

# extended colors
color16 #eec27f
color17 #e088af
  