# vim:ft=kitty

## name: ef-frost
## license: GNU
## author: Onam Hernandez


background #fcffff
foreground #232323
selection_background #dff6e4
selection_foreground #232323
url_color #00845f
cursor #232323
cursor_text_color #fcffff

# Tabs
active_tab_background #204f9a
active_tab_foreground #fcffff
inactive_tab_background #eaefef
inactive_tab_foreground #204f9a

# Windows
active_border_color #b0b7c0
inactive_border_color #eaefef

# normal
color0 #232323
color1 #c42d2f
color2 #008a00
color3 #aa6100
color4 #004fc0
color5 #aa44c5
color6 #1f6fbf
color7 #b5b8b8

# bright
color8  #66657f
color9  #d03003
color10 #468400
color11 #b6532f
color12 #4244ef
color13 #c0469a
color14 #3a6dd2
color15 #fcffff

# extended colors
color16 #996c4f
color17 #cf2f4f
  