# vim:ft=kitty

## name: ef-melissa-dark
## license: GNU
## author: Onam Hernandez


background #352718
foreground #e8e4b1
selection_background #4f311f
selection_foreground #e8e4b1
url_color #65d590
cursor #e8e4b1
cursor_text_color #352718

# Tabs
active_tab_background #ccaa70
active_tab_foreground #352718
inactive_tab_background #483426
inactive_tab_foreground #ccaa70

# Windows
active_border_color #6f5f58
inactive_border_color #483426

# normal
color0 #352718
color1 #ff7f7f
color2 #6fd560
color3 #e4b53f
color4 #57aff6
color5 #f0aac5
color6 #6fcad0
color7 #90918a

# bright
color8  #79665f
color9  #ff7f4f
color10 #a0d13a
color11 #ffa21f
color12 #98bfff
color13 #fa90aa
color14 #7fc5df
color15 #e8e4b1

# extended colors
color16 #e7a06f
color17 #ff8f98
  