# vim:ft=kitty

## name: ef-maris-light
## license: GNU
## author: Onam Hernandez


background #edf4f8
foreground #151a27
selection_background #dae5f0
selection_foreground #151a27
url_color #007047
cursor #151a27
cursor_text_color #edf4f8

# Tabs
active_tab_background #3f4f99
active_tab_foreground #edf4f8
inactive_tab_background #e0e7ef
inactive_tab_foreground #3f4f99

# Windows
active_border_color #a2a6af
inactive_border_color #e0e7ef

# normal
color0 #151a27
color1 #c3303a
color2 #007010
color3 #805a1f
color4 #375cc6
color5 #80308f
color6 #1f66af
color7 #afb8c3

# bright
color8  #676470
color9  #d00000
color10 #3a6f00
color11 #8b4400
color12 #444fcf
color13 #9a3a6a
color14 #305675
color15 #edf4f8

# extended colors
color16 #78542f
color17 #b02440
  