# vim:ft=kitty

## name: ef-orange
## license: GNU
## author: Onam Hernandez


background #ffedc9
foreground #6c4631
selection_background #ffdaa6
selection_foreground #6c4631
url_color #2f783f
cursor #6c4631
cursor_text_color #ffedc9

# Tabs
active_tab_background #8f5f4a
active_tab_foreground #ffedc9
inactive_tab_background #f7e5b6
inactive_tab_foreground #8f5f4a

# Windows
active_border_color #cfbe9b
inactive_border_color #f7e5b6

# normal
color0 #6c4631
color1 #ba2d2f
color2 #007a0a
color3 #a05a22
color4 #375cc6
color5 #ba3e54
color6 #467080
color7 #c9b088

# bright
color8  #6f6a70
color9  #c13f00
color10 #5f7200
color11 #b05115
color12 #5f50df
color13 #c32f80
color14 #3f6fa2
color15 #ffedc9

# extended colors
color16 #aa4f30
color17 #cf2030
  