# vim:ft=kitty

## name: ef-reverie
## license: GNU
## author: Onam Hernandez


background #f3eddf
foreground #4f204f
selection_background #e7d9e0
selection_foreground #4f204f
url_color #008250
cursor #4f204f
cursor_text_color #f3eddf

# Tabs
active_tab_background #55447f
active_tab_foreground #f3eddf
inactive_tab_background #e5d6d4
inactive_tab_foreground #55447f

# Windows
active_border_color #c5afb6
inactive_border_color #e5d6d4

# normal
color0 #4f204f
color1 #ba2d2f
color2 #007a0a
color3 #87591f
color4 #375cc6
color5 #9f4e74
color6 #3060af
color7 #b9aaa8

# bright
color8  #6f6877
color9  #b21f00
color10 #5a7400
color11 #a05900
color12 #5059c0
color13 #a73080
color14 #4f60a0
color15 #f3eddf

# extended colors
color16 #906045
color17 #a83058
  