# vim:ft=kitty

## name: ef-tint
## license: GNU
## author: Onam Hernandez


background #0d0e1c
foreground #ffffff
selection_background #303a6f
selection_foreground #ffffff
url_color #00c06f
cursor #ffffff
cursor_text_color #0d0e1c

# Tabs
active_tab_background #c6daff
active_tab_foreground #0d0e1c
inactive_tab_background #1d2235
inactive_tab_foreground #c6daff

# Windows
active_border_color #61647a
inactive_border_color #1d2235

# normal
color0 #0d0e1c
color1 #ff5f59
color2 #44bc44
color3 #d0bc00
color4 #2fafff
color5 #feacd0
color6 #00d3d0
color7 #989898

# bright
color8  #4a4f69
color9  #ff6b55
color10 #70b900
color11 #fec43f
color12 #79a8ff
color13 #f78fe7
color14 #4ae2f0
color15 #ffffff

# extended colors
color16 #dfaf7a
color17 #ff7f86
  