# vim:ft=kitty

## name: ef-tritanopia-dark
## license: GNU
## author: Onam Hernandez


background #15050f
foreground #dfd0d5
selection_background #3f1515
selection_foreground #dfd0d5
url_color #00b066
cursor #dfd0d5
cursor_text_color #15050f

# Tabs
active_tab_background #afdaef
active_tab_foreground #15050f
inactive_tab_background #282026
inactive_tab_foreground #afdaef

# Windows
active_border_color #555564
inactive_border_color #282026

# normal
color0 #15050f
color1 #cf4f5f
color2 #2fa526
color3 #c48702
color4 #379cf6
color5 #b0648f
color6 #3fafcf
color7 #908890

# bright
color8  #554f4f
color9  #df4f4f
color10 #64aa0f
color11 #d0730f
color12 #6a88ff
color13 #c560aa
color14 #3f9aaf
color15 #dfd0d5

# extended colors
color16 #df8f6f
color17 #d24f7f
  