# vim:ft=kitty

## name: ef-trio-dark
## license: GNU
## author: Onam Hernandez


background #160f0f
foreground #d8cfd5
selection_background #34223f
selection_foreground #d8cfd5
url_color #60bf88
cursor #d8cfd5
cursor_text_color #160f0f

# Tabs
active_tab_background #afdacf
active_tab_foreground #160f0f
inactive_tab_background #2a2228
inactive_tab_foreground #afdacf

# Windows
active_border_color #605760
inactive_border_color #2a2228

# normal
color0 #160f0f
color1 #f48359
color2 #60b444
color3 #d4a052
color4 #7fa5f6
color5 #d37faf
color6 #8fbaff
color7 #908890

# bright
color8  #564f55
color9  #ff7560
color10 #a0c27f
color11 #ef926f
color12 #8895ff
color13 #e772df
color14 #9ac2ff
color15 #d8cfd5

# extended colors
color16 #ef9680
color17 #ff85aa
  