# vim:ft=kitty

## name: ef-tritanopia-light
## license: GNU
## author: Onam Hernandez


background #fff9f9
foreground #1a1a1a
selection_background #ffdadf
selection_foreground #1a1a1a
url_color #008058
cursor #1a1a1a
cursor_text_color #fff9f9

# Tabs
active_tab_background #194f90
active_tab_foreground #fff9f9
inactive_tab_background #efecec
inactive_tab_foreground #194f90

# Windows
active_border_color #adadad
inactive_border_color #efecec

# normal
color0 #1a1a1a
color1 #aa0010
color2 #217a3c
color3 #805d00
color4 #375cd8
color5 #aa357f
color6 #2070af
color7 #bdb9b9

# bright
color8  #756275
color9  #dd0000
color10 #4a7d00
color11 #965000
color12 #4250ef
color13 #bf256a
color14 #2f5faf
color15 #fff9f9

# extended colors
color16 #765040
color17 #c50f4f
  