# vim:ft=kitty

## name: ef-winter
## license: GNU
## author: Onam Hernandez


background #0f0b15
foreground #b8c6d5
selection_background #003045
selection_foreground #b8c6d5
url_color #00a392
cursor #b8c6d5
cursor_text_color #0f0b15

# Tabs
active_tab_background #bf8a9f
active_tab_foreground #0f0b15
inactive_tab_background #1d202f
inactive_tab_foreground #bf8a9f

# Windows
active_border_color #4a4955
inactive_border_color #1d202f

# normal
color0 #0f0b15
color1 #f47359
color2 #29a444
color3 #b58a52
color4 #3f95f6
color5 #d369af
color6 #4fbaef
color7 #807c9f

# bright
color8  #4a4f62
color9  #ef6560
color10 #6aad0f
color11 #d1803f
color12 #6a9fff
color13 #e580e0
color14 #6fafdf
color15 #b8c6d5

# extended colors
color16 #df9080
color17 #ff6a7a
  