name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  stylua:
    name: Stylua Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua
  build:
    runs-on: ubuntu-latest
    name: Build Extras
    needs: stylua
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Run Build
        run: ./scripts/build
      - name: Push Changes
        if: ${{ github.event_name == 'push' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(extras): auto-generate extras"
